compile:
	npx hardhat compile

run:
	npx hardhat run ignition/modules/Escrow.ts --network sepolia

set:
	npx hardhat compile
	npx hardhat run ignition/modules/Escrow.ts --network sepolia

verify:
	npx hardhat verify --network sepolia 0xA65CB7b99f66c82d72A0eBd038874945D025cEaD 0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238